### ISSUE TITLE
Can't access buttons on the right

### ISSUE THREAD

**Issue by Asetnozama** [mdelobelle/metadatamenu#289] opened 2023-02-17 07:03 UTC
Hello,
On mobile it's not possible the change the fields, because it doesn't display the buttons on the right like on desktop. See attached image. 
![image](https://user-images.githubusercontent.com/102867794/219572866-e8ec9860-d5fb-4835-87d3-ff512e1ce6aa.jpeg)

**Comment by mdelobelle** [comment] 2023-02-18 12:37
Hi, can you try with version 0.4.20?

**Comment by Asetnozama** [comment] 2023-02-18 15:07
It's still the same

**Comment by M1chael910** [comment] 2023-06-27 22:13
I have the same issue, Any updates?

**Comment by StefanoRausch** [comment] 2023-07-01 15:19
Same here: I started to use MDM and I love it! However, on an iPhone X, I need to rotate to landscape for accessing the controls.

**Comment by mdelobelle** [comment] 2023-07-08 12:20
I'm not able to reproduce it on my Iphone 12. Could you give me the width of your display? (you can use an online tool to find it like whatismyscreenresolution.net

**Comment by StefanoRausch** [comment] 2023-07-09 11:11
I have an iPhone X Max:

- Portrait screen resolution: 414 px width x 896 px height

I will post a screenshot to show what it looks like.

**Comment by mdelobelle** [comment] 2024-02-18 10:49
This should be fixed, can you confirm?

**Closed** 2024-02-26 23:19 UTC
Labels: bug, question, solved, tags, UI
