### ISSUE TITLE
Bug in fileClasses

### ISSUE THREAD

**Issue by alancunha26** [mdelobelle/metadatamenu#275] opened 2023-02-01 22:48 UTC
Looks like all my fileClasses stop working. This console error triggers every time I call the `metadata-menu:open_fields_modal` command or when I create or edit an existing Fileclass field

![image](https://user-images.githubusercontent.com/46824739/216181590-a1ea5dba-3208-4de1-83e7-c524dc4b35f0.png)

![image](https://user-images.githubusercontent.com/46824739/216181673-f5d8d36b-e4b9-479e-a412-018a3803d239.png)

![image](https://user-images.githubusercontent.com/46824739/216181787-e8ffb10b-08b8-40e2-b7dd-e4041eed0de0.png)

**Comment by alancunha26** [comment] 2023-02-01 23:00
It seems the cursor suggester is having the same error

**Comment by alancunha26** [comment] 2023-02-01 23:19
To give more context, apparently the problem only happens when the fileClass file name includes a number (my fileClasse is `22 Projects`)

**Comment by mdelobelle** [comment] 2023-02-02 20:43
I think the dot in the fileClass name is causing this issue. Can you try to remove it and see if it fixes?

**Comment by alancunha26** [comment] 2023-02-02 20:45
What dot? I removed the number from `22 Projects` fileClass and it worked. But I think it should work even when the file has numbers in its file name.

**Comment by mdelobelle** [comment] 2023-02-02 21:02
Oh sorry, my mistake, I thought 22.1 Building my second brain was the fileClass name in your screenshot.
I've tried with a fileClass named "22 Projects" like in your example and I can't reproduce the issue, everything is owrking as expected. 
Can you test with an empty vault with just dataview and metadata menu installed?

**Comment by alancunha26** [comment] 2023-02-03 00:24
I will look into that tomorrow and get back with a response

**Comment by Morekon** [comment] 2023-05-26 13:35
I just came across the same bug. It seems to only happen for fileClasses with names that have more than one space in their name.
I also created an issue for this bug (https://github.com/mdelobelle/metadatamenu/issues/275). Sorry for opening a separate one but I did not find this issue at first.

**Comment by mdelobelle** [comment] 2023-07-08 12:07
Good catch, will be fixed in the next version

**Closed** 2023-07-21 07:09 UTC
Labels: bug, fileClass, ready to deploy
