### ISSUE TITLE
Issue with fileClass

### ISSUE THREAD

**Issue by gnosthi** [mdelobelle/metadatamenu#198] opened 2022-11-28 07:02 UTC
- Version: 0.3.9
- Install method: Obsidian Plugins
- System Info: arch x86_64
- OS: Linux
- Kernel Version: `5.15.0-46-generic #49~20.04.1-Ubuntu SMP`

 I have a fileClass called datastax-case.  This file class is working on one note but not another unless the fileClass is in frontMatter by itself. 
No other fileClass seems to have this issue. 

With fileClass in frontmatter populated with other metadata. 
![image](https://user-images.githubusercontent.com/17650528/204212825-8d31f48e-22b9-4ac2-a5c3-73741a3d52b8.png)

As you can see, the metadata menu icon does not appear. 

However, if I place the fileClass in frontmatter by itself it works. 
![image](https://user-images.githubusercontent.com/17650528/204212935-ade112d5-0610-4b31-99b3-61713a2aba96.png)

However, even if I  join the working fileClass with the existing  frontmatter it stops working again. 
![image](https://user-images.githubusercontent.com/17650528/204213189-075ec39e-6f74-4d57-a41c-bc6cb06a29d4.png)

The only thing changed in the above picture was to remove the dividers and remove the existing fileClass parameter from the old frontmatter. 

It just seems to be this one note. 

I am also using tag based fileClass as well. But that seems to have stopped working even for other notes. 

However, I do have case notes which work fine. 
![image](https://user-images.githubusercontent.com/17650528/204213650-604aa889-96bc-439c-8a2b-4a0759866ac7.png)

Here is the fileClass definition
```
---
mapWithTag: true
tagNames: []
---

case_id:: {"type":"Input","options":{}}
salesforce_link:: {"type":"Input","options":{}}
related_cases:: {"type":"MultiFile","options":{}}
customer:: {"type":"Select","options":{"valuesList":{},"sourceType":"ValuesListNotePath","valuesListNotePath":"Templates/Lists/DataStax Customer List Values.md","valuesFromDVQuery":""}}
product:: {"type":"Multi","options":{"valuesList":{},"sourceType":"ValuesListNotePath","valuesListNotePath":"Templates/Lists/DataStax Product List Values.md","valuesFromDVQuery":""}}
astra_clusters:: {"type":"Input","options":{}}
issue_summary:: {"type":"Input","options":{}}
issue_type:: {"type":"Multi","options":{"valuesList":{"1":"KMIP"},"sourceType":"ValuesList","valuesListNotePath":"","valuesFromDVQuery":""}}
incident:: {"type":"Boolean","options":{}}
status:: {"type":"Select","options":{"valuesList":{"1":"new","2":"investigating","3":"handoff","4":"resolved"},"sourceType":"ValuesList","valuesListNotePath":"","valuesFromDVQuery":""}}
pd_alert:: {"type":"Input","options":{}}
jira_issues:: {"type":"Input","options":{}}
case_subject:: {"type":"Input","options":{}}
product_versions:: {"type":"Multi","options":{"valuesList":{},"sourceType":"ValuesListNotePath","valuesListNotePath":"Templates/Lists/DataStax Product Version List.md","valuesFromDVQuery":""}}
```
Here is the case template
```
<%* 
let title = tp.file.title 
if (title.startsWith("Untitled")) {
title = await tp.system.prompt("Title");
}
await tp.file.rename(title) -%>

<% tp.file.include("[[DataStax Case Frontmatter Template]]") %>

# <% title %>

>[!INFO] Case Info
>case_id:: <% title %>
>case_subject:: <% tp.system.prompt("Case Subject") %>
>salesforce_link:: <% tp.system.prompt("Salesforce Link") %>
>related_cases::
>customer::
>product::
>product_versions:: 
>astra_clusters:: <% tp.system.prompt("Astra Cluster") %>
>issue_summary:: <% tp.system.prompt("Issue Summary?") %>
>issue_type::
>incident::
>pd_alert::
>jira_issues::
>status::

## Issue Synopsis



## Working Notes
<% tp.file.include("[[Datastax Case - Working Notes Template]]") %>


## Artifacts

``````col
`````col-md
flexGrow: 2.0
===
#### jira Links:

#### Slack Links:

#### Documentation:
`````
`````col-md
flexGrow=3.5
===
#### file links:

#### Possibly Related Cases
```dataview
TABLE case_subject,product_versions,issue_summary,issue_type FROM #datastax-case AND !"Templates" WHERE issue_type = this.issue_type
```

`````

``````





## Generated Documentation




## Resolution Notes


------------------------------------------------

## Metadata fileClass
#datastax-case
```
Please let me know if you need further information. 

Thank you.

**Comment by mdelobelle** [comment] 2022-11-28 19:38
Hi, I think there's a problem with your record/purpose field: it lacks an ending quote. Therefore the frontmatter is considered as invalid

Could you fix it and try again?

**Comment by mdelobelle** [comment] 2022-12-09 13:37
any chance to test this?
i can't reproduce the issue. I'll close it for now

**Closed by mdelobelle** 2022-12-09 13:37 UTC
Labels: question
