### ISSUE TITLE
Save bug

### ISSUE THREAD

**Issue by DannyHatcher-Git** [mdelobelle/metadatamenu#227] opened 2022-12-30 17:23 UTC
When I try and save the settings for a fileclass nothing happens.

I am following your most recent YouTube video but the settings don't get saved.

**Comment by mdelobelle** [comment] 2022-12-30 17:54
Hi, can you give me the following details please?
- which kind of setting or field type are you trying to include? (is it happening only for one type or for all?)
- where are you updating those settings from? (from the fileClass view > fileClass setting tab? from the context menu of a fileClass?...)
- What's the name of the fileClass? 
- do you have a fileClassAlias? (if so, what is it?)
- do you see any error in the developer console?
- can you paste the raw content of the fileClass file?

**Comment by mdelobelle** [comment] 2022-12-30 17:56
One last question: are you trying to save it from the mobile app or from the desktop app?

**Comment by DannyHatcher-Git** [comment] 2022-12-30 18:03
I have made a file in a folder called fileclass

Then tried to Map with tag and save, but nothing saves.
![image](https://user-images.githubusercontent.com/78496825/210099784-409d3350-8873-4ee1-95f7-40c7482acaff.png)

**Comment by mdelobelle** [comment] 2022-12-30 18:22
I've tried to reproduce that from a fresh vault and it worked as expected.

Maybe except a hiccup with indexing: I had to disable/enable the plugin to trigger the indexing correctly (due to the sequence dataview>metadata menu loading it's sometimes not fully indexed) -> maybe you could try that 

BTW: Do you see any error in the developer console?

**Comment by DannyHatcher-Git** [comment] 2022-12-30 18:37
https://user-images.githubusercontent.com/78496825/210102162-068bf75a-7303-4c71-968b-def255f34d54.mp4

**Comment by mdelobelle** [comment] 2022-12-30 18:54
Thanks a lot!
I see that you are running the windows app. I'll try on that platform as soon as i can.

**Comment by mdelobelle** [comment] 2022-12-30 20:36
got it!
i think uour Task.canvas file is empty and therés an error reading empty canvas (this shouldn't be blocking, I have to fix that)
Could you remove your Tasks.canvas or just add a dummy node in it to check if that solves the issue please?

**Comment by mdelobelle** [comment] 2022-12-30 20:44
woops, wrong idea: I was testing on an old branch...
I'm still digging: everything seems to be working as expected on windows 10

**Comment by mdelobelle** [comment] 2022-12-30 20:48
oh! you don't have dataview installed? Can you try to install and enable dataview and enable DataviewJS queries in their settings?

**Comment by DannyHatcher-Git** [comment] 2022-12-30 21:09
ah. I didn't realise you need dataview for this plugin

**Comment by mdelobelle** [comment] 2022-12-30 22:17
I'll add a Notice at the plugin loading and I will make it explicit in the documentation and readMe.

**Comment by mdelobelle** [comment] 2022-12-31 13:32
Is it working?

**Comment by DannyHatcher-Git** [comment] 2022-12-31 14:26
Yes, it is now. That is what the thumb up was for fyi 😁

**Comment by mdelobelle** [comment] 2022-12-31 14:44
Great! I,ll close this issue then. Don't hesitate to give me some feedback and ideas if you have the time to dig into this plugin.

**Closed** 2022-12-31 14:44 UTC
