### ISSUE TITLE
Map with tag no longer working

### ISSUE THREAD

**Issue by kmaustral** [mdelobelle/metadatamenu#424] opened 2023-11-08 22:39 UTC
With 0.6.0 beta version, the map with tag function is not working. The fields cannot be edited from the modal either.

**Comment by mdelobelle** [comment] 2023-11-08 23:06
Have you tried the latest release 0.6.0-beta-4?

**Comment by kmaustral** [comment] 2023-11-09 00:25
Yes. This is in my console:
<img width="401" alt="image" src="https://github.com/mdelobelle/metadatamenu/assets/73867063/a54df5e1-cfed-46ed-b8d8-b99cadbf3b8c">

**Comment by kmaustral** [comment] 2023-11-09 00:31
That's when I try to edit from the modal. There are no icons anymore, either.

**Comment by kmaustral** [comment] 2023-11-09 00:45
Update. The fields did eventually open for the modal, but about five minutes later. There's a significant lag in it opening.

**Comment by kmaustral** [comment] 2023-11-09 01:39
After about an hour of use, the modal is now operating fine.

**Comment by mdelobelle** [comment] 2023-11-09 05:05
let's try to improve that

dufing all this time did you notice the indexing status (little folder icon with a blue rotating icon in the status bar)?
If yes it means that the plugin took all that time to index the fields values which is very long

It may be caused by:
- heavy md files (md files > 100Ko)
- lots of "calculated fields" (lookups or formulas)

Are you in one of these case?
How many files do you have in your vault?

**Comment by kmaustral** [comment] 2023-11-09 07:13
I have around 15k files. I don't have any formulas that I'm aware of.

**Comment by mdelobelle** [comment] 2023-11-09 16:16
can you try with this new release and see if it improves the launch time? 
https://github.com/mdelobelle/metadatamenu/releases/tag/0.6.0-beta-5

**Comment by kmaustral** [comment] 2023-11-09 23:16
I tried it out. It didn't seem to decrease the time in opening up the model
field - about five minutes.

**Comment by mdelobelle** [comment] 2023-12-01 21:52
Is it fixed with the latest version?

**Comment by kmaustral** [comment] 2023-12-02 05:02
Yes, it's working fine now thank you.

**Closed** 2023-12-02 05:22 UTC
Labels: solved, performance
