### ISSUE TITLE
MultiMedia not displayed in Table view

### ISSUE THREAD

**Issue by SourignaSimmalavong** [mdelobelle/metadatamenu#625] opened 2024-03-05 21:56 UTC
Hello,

In the table view, for MultiMedia fields, the images are not displayed anymore, only their links.
I would expect images to be displayed in the Table View.

Using Metadata-Menu 0.8.4 (and Obsidian 1.5.8) in the sandbox vault:
![image](https://github.com/mdelobelle/metadatamenu/assets/47475038/0453b669-753c-4bf7-bc1e-b2134924f164)

Using Metadata-Menu 0.7.7:
![image](https://github.com/mdelobelle/metadatamenu/assets/47475038/d43b631f-d302-4e97-bd36-dbed748605b5)

The same applies when adding several images.

Using Metadata-Menu 0.8.4:
![image](https://github.com/mdelobelle/metadatamenu/assets/47475038/34378e13-fe8e-4093-8ddd-7baf9922e51f)

Using Metadata-Menu 0.7.7:
![image](https://github.com/mdelobelle/metadatamenu/assets/47475038/d4439e85-a994-4485-89d4-fce9aea84641)

Thank you!

**Comment by mdelobelle** [comment] 2024-03-23 09:33
Hi I can't reproduce this. Can you paste the yaml definition of your fileclass please?

**Comment by mdelobelle** [comment] 2024-03-23 13:17
good catch. will be fixed in 0.8.6

**Comment by mdelobelle** [comment] 2024-03-23 13:24
fixed in 0.8.6

**Comment by SourignaSimmalavong** [comment] 2024-03-28 19:34
Thank you, I tested it with 0.8.7 and it works 👍
The thumbnail is a bit small ( `width: 40px` ) but that's easily tweakable with a bit of CSS.

**Closed** 2024-03-29 02:54 UTC
Labels: bug, YAML fields, fileClass view, waiting for confirmation
