### ISSUE TITLE
Boolean expressions break the modal menu

### ISSUE THREAD

**Issue by AucklandIO** [mdelobelle/metadatamenu#471] opened 2023-12-03 17:29 UTC
Inserting single or multiple missing boolean properties breaks the modal menu.

Expected Behaviour:
Boolean expressions are inserted into the front matter and can be toggled true or false by their icon.

Broken Behaviour:
No matter how many boolean properties are added, only one (randomly selected boolean option) is listed, all non-frontmatter properties are removed from the modal menu, and the boolean is not toggleable.

How to repeat:
I have reverted back to 0.6.4. This is latest version that does not have this bug.

**Comment by mdelobelle** [comment] 2023-12-03 17:36
Can you paste your fileClass frontmatter here please? I can't reproduce the issue:
<img width="1037" alt="image" src="https://github.com/mdelobelle/metadatamenu/assets/1233240/6016e034-043c-4376-a9d2-eaeccc03c6a8">
<img width="1039" alt="image" src="https://github.com/mdelobelle/metadatamenu/assets/1233240/491da78a-b2e2-4f24-8123-b44bf9468c3c">
The toggle seems to work fine in prorperties section

<img width="1041" alt="image" src="https://github.com/mdelobelle/metadatamenu/assets/1233240/4fe43c35-d961-42f3-bbe2-eb29b8739dfe">
<img width="1036" alt="image" src="https://github.com/mdelobelle/metadatamenu/assets/1233240/fc80222b-4e5f-4fcc-ae46-9a9c17238b0e">
And the note modal seems to work fine as well

**Comment by CountRucula** [comment] 2024-01-12 17:07
I had the same problem.

A look in the developer options helped me find the issue:
![image](https://github.com/mdelobelle/metadatamenu/assets/67362815/fc7aa602-d871-48b9-8d18-61baa3fe56f1)

Replacing the space in the filename of the FileClass-file with an underscore fixed it for me.
"/Studium/Note FileClass" -> "/Studium/Note_FileClass"

Hope it helps :)

**Comment by mdelobelle** [comment] 2024-02-18 13:45
Good catch. will be fixed in the next release

**Comment by mdelobelle** [comment] 2024-02-18 13:53
fixed in 0.8.1

**Closed by mdelobelle** 2024-02-18 13:53 UTC
Labels: bug, fileClass, Done waiting for release
